### ISSUE TITLE
Every so often `AnalyticsClient::performQuery()` hangs forever

### ISSUE THREAD

**Issue by oppiansteve** [spatie/laravel-analytics#381] opened 2021-01-04 16:30 UTC
Using:
spatie/laravel-analytics 3.10.2
google/apiclient v2.8.3

This happens every few hundred requests for us and sometimes more often.
It started a couple of weeks ago and I've now get a system in place to kill these jobs that hang forever.

I'll try to debug this fully and fix my own ticket, but raising in case anyone can provide any help.

I notice that in `AnalyticsClient::performQuery()` there's ample opportunity for an infinite while loop to happen if this logic is no longer correct:

```
            while ($nextLink = $result->getNextLink()) {
                if (isset($others['max-results']) && count($result->rows) >= $others['max-results']) {
                    break;
                }

                $options = [];

                parse_str(substr($nextLink, strpos($nextLink, '?') + 1), $options);

                $response = $this->service->data_ga->call('get', [$options], 'Google_Service_Analytics_GaData');

                if ($response->rows) {
                    $result->rows = array_merge($result->rows, $response->rows);
                }

                $result->nextLink = $response->nextLink;
            }
```

**Comment by appdezign** [comment] 2021-01-04 16:37
I have the exact same problem, and I have spent hours trying to figure this out.
For me this happens quite often.

Als using:
spatie/laravel-analytics 3.10.2
google/apiclient v2.8.3

**Comment by oppiansteve** [comment] 2021-01-04 18:02
Interestingly it seems that loop isn't to blame - this is the line that sometimes never returns:

```
            $result = $this->service->data_ga->get(
                "ga:{$viewId}",
                $startDate->format('Y-m-d'),
                $endDate->format('Y-m-d'),
                $metrics,
                $others
            );
```

So perhaps not as easy as I thought

**Comment by oppiansteve** [comment] 2021-01-04 18:32
OK, so it is just a Guzzle get request that the SDK makes that never returns - if I set the guzzle client to have sane timeouts, it times out at the right time.

I set the `connect_timeout`, the `read_timeout` and the `timeout` and in this case it was the `timeout` that was hit.

So, I'll see what the best way is of configuring the guzzle client for custom options via the spatie laravel analytics wrapper and create a pull request if I come up with somethine nicely generic.

(As a bonus measure, I may see if I can also configure the Google API logger as that sounds useful,  although that will probably be on another pull request, of course)

**Comment by appdezign** [comment] 2021-01-04 18:34
That makes sense. My problems started when I upgraded to Laravel 8, which means an upgrade from guzzle 6 to 7.

**Comment by oppiansteve** [comment] 2021-01-04 18:35
Another thing that would be useful, would be to allow configuring of the guzzle client middleware - and also add a retrier - so when it does timeout, it will retry a certain number of times.

**Comment by oppiansteve** [comment] 2021-01-04 18:35
I dropped back from guzzle 7 to guzzle 6 (which works with Laravel 8, but isn't recommended) and that didn't actually help at all, which surprised me.

**Comment by appdezign** [comment] 2021-01-04 19:22
I've done some more testing, and my older applications (which still use Guzzle 6) have the same problem. So my earlier conclusion that this was caused by the upgrade to Guzzle 7 seems to be wrong.

What still puzzles me, is the question what has changed in the past few weeks. Apart from the fact that the timeouts should be handled correctly in this plugin, I still do not understand why we suddenly expericence so many timouts on the Google API. I have dozens of applications that use this plugin since 2018, and I have never seen this before.

**Comment by oppiansteve** [comment] 2021-01-04 19:24
I'm not sure how much more time I'll have to work on this in the near future, but here's what has worked for me:

I've changed the code from:
```
protected function getLaravelAnalytics(string $site_id)
{
    $config = config('analytics');
    $config['view_id'] = str_replace('ga:', '', strtolower($site_id));

    return new Analytics(
        AnalyticsClientFactory::createForConfig(
            $config
        ),
        $config['view_id']
    );
}
```

To:
```
protected function getLaravelAnalytics(string $site_id)
{
    $config = config('analytics');
    $config['view_id'] = str_replace('ga:', '', strtolower($site_id));

    $analytics_client = AnalyticsClientFactory::createForConfig($config);

    $analytics_client->getAnalyticsService()
        ->getClient()
        ->setHttpClient(
            new GuzzleClient([
                'base_uri' => Google_Client::API_BASE_PATH,
                'http_errors' => false,
                'connect_timeout' => config('xxx.connect_timeout'),
                'read_timeout' => config('xxx.read_timeout'),
                'timeout' => config('xxx.timeout'),
            ])
        );

    return new Analytics(
        $analytics_client,
        $config['view_id']
    );
}
```

Hope that helps for your use-case, @appdezign

**Comment by appdezign** [comment] 2021-01-04 19:39
I will try to implement your workaround in my application. Thanks for now, @oppiansteve

**Comment by mbardelmeijer** [comment] 2021-01-04 20:11
See https://github.com/spatie/laravel-analytics/discussions/378 & https://issuetracker.google.com/issues/176032263

It's a known issue @ Google Analytics API, and they say they are working on it. Taking a long time tho.

**Comment by oppiansteve** [comment] 2021-01-04 20:48
Good to know - I wouldn't say slow, however, as I've waited for >15 hours and not had a timeout or response.
That seems more than slow :-)

**Comment by appdezign** [comment] 2021-01-05 13:47
I think this can be easily fixed with a minor change in createAuthenticatedGoogleClient()

Change (AnalyticsClientFactory.php) line 24 from:

```
    $client = new Google_Client();
```

to:
```
    $client = new Google_Client();

    $http = new \GuzzleHttp\Client([
        'timeout' => $config['timeout']
    ]);
    $client->setHttpClient($http);
```

And the 'timeout' key should be added to the config of course (with a default value of 0).

**Comment by tomgoethuys** [comment] 2021-01-15 09:20
Google marked this issue as fixed

> Thank you for your patience on this issue.

The team has declared this issue fixed, but we are also still monitoring the performance of the API as well. Kindly try doing queries on the API once more, and do not hesitate to reach out to us again if you still encounter any issues with this.

**Closed** 2021-03-26 14:30 UTC
