### ISSUE TITLE
curl error 60

### ISSUE THREAD

**Issue by metinbulak** [spatie/laravel-analytics#193] opened 2017-06-23 23:16 UTC
thank you for laravel-analytics 
I use analytics in localhost and I get this error cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

can anyone help me.

**Comment by tallrye** [comment] 2017-06-30 10:39
Hi,

Please see: https://github.com/google/google-api-php-client/issues/843 

Hope this helps.

**Comment by freekmurze** [comment] 2017-06-30 11:01
Closing this as the problem is probably more related to google-api-php

**Closed by freekmurze** 2017-06-30 11:01 UTC
